const a = 1;
try {
} catch (e) {
  a;
}
